# Generated by Django 3.2 on 2023-03-17 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=30)),
                ('descripcion_titulo', models.CharField(max_length=80)),
                ('subtitulo', models.CharField(max_length=10)),
                ('descripcion', models.CharField(max_length=150)),
            ],
        ),
    ]
